pub static OPCODES: [&'static str; 0x100] = [
    // Opcodes 0X
  "NOP",
  "LD BC, NN",
  "LD [BC], A",
  "INC BC",
  "INC B",
  "DEC B",
  "LD B, N",
  "RLCA",
  "LD [NN], SP",
  "ADD HL, BC",
  "LD A, [BC]",
  "DEC BC",
  "INC C",
  "DEC C",
  "LD C, N",
  "RRCA",
  // Opcodes 1X
  "STOP",
  "LD DE, NN",
  "LD [DE], A",
  "INC DE",
  "INC D",
  "DEC D",
  "LD D, N",
  "RLA",
  "JR SN",
  "ADD HL, DE",
  "LD A, [DE]",
  "DEC DE",
  "INC E",
  "DEC E",
  "LD E, N",
  "RRA",
  // Opcodes 2X
  "JR NZ, SN",
  "LD HL, NN",
  "LDI [HL], A",
  "INC HL",
  "INC H",
  "DEC H",
  "LD H, N",
  "DAA",
  "JR Z, SN",
  "ADD HL, HL",
  "LDI A, [HL]",
  "DEC HL",
  "INC L",
  "DEC L",
  "LD L, N",
  "CPL",
  // Opcodes 3X
  "JR NC, SN",
  "LD SP, NN",
  "LDD [HL], A",
  "INC SP",
  "INC [HL]",
  "DEC [HL]",
  "LD [HL], N",
  "SCF",
  "JR C, SN",
  "ADD HL, SP",
  "LDD A, [HL]",
  "DEC SP",
  "INC A",
  "DEC A",
  "LD A, N",
  "CCF",
  // Opcodes 4X
  "LD B, B",
  "LD B, C",
  "LD B, D",
  "LD B, E",
  "LD B, H",
  "LD B, L",
  "LD B, [HL]",
  "LD B, A",
  "LD C, B",
  "LD C, C",
  "LD C, D",
  "LD C, E",
  "LD C, H",
  "LD C, L",
  "LD C, [HL]",
  "LD C, A",
  // Opcodes 5X
  "LD D, B",
  "LD D, C",
  "LD D, D",
  "LD D, E",
  "LD D, H",
  "LD D, L",
  "LD D, [HL]",
  "LD D, A",
  "LD E, B",
  "LD E, C",
  "LD E, D",
  "LD E, E",
  "LD E, H",
  "LD E, L",
  "LD E, [HL]",
  "LD E, A",
  // Opcodes 6X
  "LD H, B",
  "LD H, C",
  "LD H, D",
  "LD H, E",
  "LD H, H",
  "LD H, L",
  "LD H, [HL]",
  "LD H, A",
  "LD L, B",
  "LD L, C",
  "LD L, D",
  "LD L, E",
  "LD L, H",
  "LD L, L",
  "LD L, [HL]",
  "LD L, A",
  // Opcodes 7X
  "LD [HL], B",
  "LD [HL], C",
  "LD [HL], D",
  "LD [HL], E",
  "LD [HL], H",
  "LD [HL], L",
  "HALT",
  "LD [HL], A",
  "LD A, B",
  "LD A, C",
  "LD A, D",
  "LD A, E",
  "LD A, H",
  "LD A, L",
  "LD A, [HL]",
  "LD A, A",
  // Opcodes 8X
  "ADD A, B",
  "ADD A, C",
  "ADD A, D",
  "ADD A, E",
  "ADD A, H",
  "ADD A, L",
  "ADD A, [HL]",
  "ADD A, A",
  "ADC A, B",
  "ADC A, C",
  "ADC A, D",
  "ADC A, E",
  "ADC A, H",
  "ADC A, L",
  "ADC A, [HL]",
  "ADC A, A",
  // Opcodes 9X
  "SUB A, B",
  "SUB A, C",
  "SUB A, D",
  "SUB A, E",
  "SUB A, H",
  "SUB A, L",
  "SUB A, [HL]",
  "SUB A, A",
  "SBC A, B",
  "SBC A, C",
  "SBC A, D",
  "SBC A, E",
  "SBC A, H",
  "SBC A, L",
  "SBC A, [HL]",
  "SBC A, A",
  // Opcodes AX
  "AND A, B",
  "AND A, C",
  "AND A, D",
  "AND A, E",
  "AND A, H",
  "AND A, L",
  "AND A, [HL]",
  "AND A, A",
  "XOR A, B",
  "XOR A, C",
  "XOR A, D",
  "XOR A, E",
  "XOR A, H",
  "XOR A, L",
  "XOR A, [HL]",
  "XOR A, A",
  // Opcodes BX
  "OR A, B",
  "OR A, C",
  "OR A, D",
  "OR A, E",
  "OR A, H",
  "OR A, L",
  "OR A, [HL]",
  "OR A, A",
  "CP A, B",
  "CP A, C",
  "CP A, D",
  "CP A, E",
  "CP A, H",
  "CP A, L",
  "CP A, [HL]",
  "CP A, A",
  // Opcodes CX
  "RET NZ",
  "POP BC",
  "JP NZ, NN",
  "JP NN",
  "CALL NZ, NN",
  "PUSH BC",
  "ADD A, N",
  "RST 00",
  "RET Z",
  "RET",
  "JP Z, NN",
  "UNDEFINED", // See bitops opcode map
  "CALL Z, NN",
  "CALL NN",
  "ADC A, N",
  "RST 08",
  // Opcodes DX
  "RET NC",
  "POP DE",
  "JP NC, NN",
  "UNDEFINED",
  "CALL NC, NN",
  "PUSH DE",
  "SUB A, N",
  "RST 10",
  "RET C",
  "RETI",
  "JP C, NN",
  "UNDEFINED",
  "CALL C, NN",
  "UNDEFINED",
  "SBC A, N",
  "RST 18",
  // Opcodes EX
  "LDH [N], A",
  "POP HL",
  "LDH [C], A",
  "UNDEFINED",
  "UNDEFINED",
  "PUSH HL",
  "AND A, N",
  "RST 20",
  "ADD SP, SN",
  "JP HL",
  "LD [NN], A",
  "UNDEFINED",
  "UNDEFINED",
  "UNDEFINED",
  "XOR A, N",
  "RST 28",
  // Opcodes FX
  "LDH A, [N]",
  "POP AF",
  "LDH A, [C]",
  "DI",
  "UNDEFINED",
  "PUSH AF",
  "OR A, N",
  "RST 30",
  "LD HL, SP, SN",
  "LD SP, HL",
  "LD A, [NN]",
  "EI",
  "UNDEFINED",
  "UNDEFINED",
  "CP A, N",
  "RST 38",
];

pub static BIT_OPCODES: [&'static str; 0x100] = [
        // Opcodes CB 0X
  "RLC B",
  "RLC C",
  "RLC D",
  "RLC E",
  "RLC H",
  "RLC L",
  "RLC [HL]",
  "RLC A",
  "RRC B",
  "RRC C",
  "RRC D",
  "RRC E",
  "RRC H",
  "RRC L",
  "RRC [HL]",
  "RRC A",
        // Opcodes CB 1X
  "RL B",
  "RL C",
  "RL D",
  "RL E",
  "RL H",
  "RL L",
  "RL [HL]",
  "RL A",
  "RR B",
  "RR C",
  "RR D",
  "RR E",
  "RR H",
  "RR L",
  "RR [HL]",
  "RR A",
        // Opcodes CB 2X
  "SLA B",
  "SLA C",
  "SLA D",
  "SLA E",
  "SLA H",
  "SLA L",
  "SLA [HL]",
  "SLA A",
  "SRA B",
  "SRA C",
  "SRA D",
  "SRA E",
  "SRA H",
  "SRA L",
  "SRA [HL]",
  "SRA A",
        // Opcodes CB 3X
  "SWAP B",
  "SWAP C",
  "SWAP D",
  "SWAP E",
  "SWAP H",
  "SWAP L",
  "SWAP [HL]",
  "SWAP A",
  "SRL B",
  "SRL C",
  "SRL D",
  "SRL E",
  "SRL H",
  "SRL L",
  "SRL [HL]",
  "SRL A",
        // Opcodes CB 4X
  "BIT B, 0",
  "BIT C, 0",
  "BIT D, 0",
  "BIT E, 0",
  "BIT H, 0",
  "BIT L, 0",
  "BIT [HL], 0",
  "BIT A, 0",
  "BIT B, 1",
  "BIT C, 1",
  "BIT D, 1",
  "BIT E, 1",
  "BIT H, 1",
  "BIT L, 1",
  "BIT [HL], 1",
  "BIT A, 1",
        // Opcodes CB 5X
  "BIT B, 2",
  "BIT C, 2",
  "BIT D, 2",
  "BIT E, 2",
  "BIT H, 2",
  "BIT L, 2",
  "BIT [HL], 2",
  "BIT A, 2",
  "BIT B, 3",
  "BIT C, 3",
  "BIT D, 3",
  "BIT E, 3",
  "BIT H, 3",
  "BIT L, 3",
  "BIT [HL], 3",
  "BIT A, 3",
        // Opcodes CB 6X
  "BIT B, 4",
  "BIT C, 4",
  "BIT D, 4",
  "BIT E, 4",
  "BIT H, 4",
  "BIT L, 4",
  "BIT [HL], 4",
  "BIT A, 4",
  "BIT B, 5",
  "BIT C, 5",
  "BIT D, 5",
  "BIT E, 5",
  "BIT H, 5",
  "BIT L, 5",
  "BIT [HL], 5",
  "BIT A, 5",
        // Opcodes CB 7X
  "BIT B, 6",
  "BIT C, 6",
  "BIT D, 6",
  "BIT E, 6",
  "BIT H, 6",
  "BIT L, 6",
  "BIT [HL], 6",
  "BIT A, 6",
  "BIT B, 7",
  "BIT C, 7",
  "BIT D, 7",
  "BIT E, 7",
  "BIT H, 7",
  "BIT L, 7",
  "BIT [HL], 7",
  "BIT A, 7",
        // Opcodes CB 8X
  "RES B, 0",
  "RES C, 0",
  "RES D, 0",
  "RES E, 0",
  "RES H, 0",
  "RES L, 0",
  "RES [HL], 0",
  "RES A, 0",
  "RES B, 1",
  "RES C, 1",
  "RES D, 1",
  "RES E, 1",
  "RES H, 1",
  "RES L, 1",
  "RES [HL], 1",
  "RES A, 1",
        // Opcodes CB 9X
  "RES B, 2",
  "RES C, 2",
  "RES D, 2",
  "RES E, 2",
  "RES H, 2",
  "RES L, 2",
  "RES [HL], 2",
  "RES A, 2",
  "RES B, 3",
  "RES C, 3",
  "RES D, 3",
  "RES E, 3",
  "RES H, 3",
  "RES L, 3",
  "RES [HL], 3",
  "RES A, 3",
        // Opcodes CB AX
  "RES B, 4",
  "RES C, 4",
  "RES D, 4",
  "RES E, 4",
  "RES H, 4",
  "RES L, 4",
  "RES [HL], 4",
  "RES A, 4",
  "RES B, 5",
  "RES C, 5",
  "RES D, 5",
  "RES E, 5",
  "RES H, 5",
  "RES L, 5",
  "RES [HL], 5",
  "RES A, 5",
        // Opcodes CB BX
  "RES B, 6",
  "RES C, 6",
  "RES D, 6",
  "RES E, 6",
  "RES H, 6",
  "RES L, 6",
  "RES [HL], 6",
  "RES A, 6",
  "RES B, 7",
  "RES C, 7",
  "RES D, 7",
  "RES E, 7",
  "RES H, 7",
  "RES L, 7",
  "RES [HL], 7",
  "RES A, 7",
        // Opcodes CB CX
  "SET B, 0",
  "SET C, 0",
  "SET D, 0",
  "SET E, 0",
  "SET H, 0",
  "SET L, 0",
  "SET [HL], 0",
  "SET A, 0",
  "SET B, 1",
  "SET C, 1",
  "SET D, 1",
  "SET E, 1",
  "SET H, 1",
  "SET L, 1",
  "SET [HL], 1",
  "SET A, 1",
        // Opcodes CB DX
  "SET B, 2",
  "SET C, 2",
  "SET D, 2",
  "SET E, 2",
  "SET H, 2",
  "SET L, 2",
  "SET [HL], 2",
  "SET A, 2",
  "SET B, 3",
  "SET C, 3",
  "SET D, 3",
  "SET E, 3",
  "SET H, 3",
  "SET L, 3",
  "SET [HL], 3",
  "SET A, 3",
        // Opcodes CB EX
  "SET B, 4",
  "SET C, 4",
  "SET D, 4",
  "SET E, 4",
  "SET H, 4",
  "SET L, 4",
  "SET [HL], 4",
  "SET A, 4",
  "SET B, 5",
  "SET C, 5",
  "SET D, 5",
  "SET E, 5",
  "SET H, 5",
  "SET L, 5",
  "SET [HL], 5",
  "SET A, 5",
        // Opcodes CB FX
  "SET B, 6",
  "SET C, 6",
  "SET D, 6",
  "SET E, 6",
  "SET H, 6",
  "SET L, 6",
  "SET [HL], 6",
  "SET A, 6",
  "SET B, 7",
  "SET C, 7",
  "SET D, 7",
  "SET E, 7",
  "SET H, 7",
  "SET L, 7",
  "SET [HL], 7",
  "SET A, 7",
];